# Generated by Django 5.0.2 on 2024-03-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackproblem', '0006_alter_comment_author_alter_issue_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
